services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projeto_a_database
    volumes:
      - projeto_a_database_data:/postgres/data
  projeto-a-back:
    container_name: projeto-a-back
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - .env
volumes:
  projeto_a_database_data:
